Repository JDaniielC/IS-project-2020.2, pull requests merged in 2022-03, with the labels that each got.

#16 Feature/issue 9
  kernel.asm
Labels: enhancement

#21 SO logo
  boot2.asm
Labels: good first issue

#23 [8] Menu apps
  kernel.asm
  menu.asm
Labels: good first issue

#24 Menu and Browser works
  boot2.asm
  kernel.asm
  menu.asm
Labels: good first issue

#17 Feature/issue 11
  kernel.asm
Labels: enhancement

#18 feature/issue-13
  kernel.asm
Labels: good first issue

#12 Notes base
  boot1.asm
  kernel.asm
Labels: good first issue

#26 Create LICENSE
  LICENSE
Labels: documentation

#22 SO about app
  kernel.asm
Labels: good first issue

#29 Link prompt with kernel
  kernel.asm
  terminal.asm
Labels: good first issue

#30 Falta ajustes
  kernel.asm
Labels: help wanted

#32 Feature/issue 5
  kernel.asm
Labels: help wanted

#33 Color adjustments
  kernel.asm
Labels: documentation

#34 Initial commit README
  .github/initialGif.gif
  .github/lastGif.gif
  README.md
Labels: documentation

#36 Background and center text app
  kernel.asm
Labels: enhancement
